<?php
  include 'header.php';
?>
      <!-- Card-->
      <div class="container">
        <div class="card mt-5">
          <div class="card-header">
            Bản đồ
          </div>
          <div class="card-body">
            <h5 class="card-title">Chào mừng bạn đến với trang web của tôi</h5>
            <p class="card-text">Trang chủ của chúng tôi đang cập nhật. Xin lỗi vì sự bất tiện này</p>
          </div>
        </div>
      </div>
    <div>
<?php
  include 'footer.php';
  include 'js.php';
?>